- README.md
- generate.xml
- templates/gsl.Makefile.am
- templates/gsl.configure.ac
- templates/gsl.install.sh
- templates/gsl.packages.config
- utilities.gsl
Adds a quick start in the README.md
> Adds png and qrencode build support

- generate.xml
Version bumps png from 1.6.25 to 1.6.27
> Version bumps zlib from 1.2.8 to 1.2.9

- templates/gsl.install.sh
> Echo errors to stderr.

- templates/gsl.travis.yml
Fixes explicit clang-3.4 dependency as well as code coverage/coveralls.io integration.
> Correct dependency installation issues.

- generate.xml
- templates/gsl.install.sh
- utilities.gsl
See https://github.com/libbitcoin/libbitcoin-server/pull/430
> Download ZMQ tarball version 4.2.3

- templates/common_msvc_artifacts.gsl
- templates/gsl.vcxproj
- templates/gsl.vcxproj.filters
- templates/vs2013/gsl.vcxproj
- templates/vs2013/gsl.vcxproj.filters
- templates/vs2015/gsl.vcxproj
- templates/vs2015/gsl.vcxproj.filters
- templates/vs2017/gsl.vcxproj
- templates/vs2017/gsl.vcxproj.filters
(restricted to libbitcoin library project, vs2013).
> Correct conditions for src/external filter inclusion

- templates/gsl.install.sh
(cherry picked from commit 198589499f4f692e03b1a99aeb68c31c2f2a84a1)
> Add --help option response to generated install.sh

- templates/gsl.install.sh
until options are discovered recursively.
(cherry picked from commit 7b37aef940c752cd21f874e6a237bbe1f10fe294)
> Add exception for libbitcoin-consensus documentation

- templates/gsl.install.sh
(cherry picked from commit 5277deb9a681f2e444f88de6a0af1929daa36a67)
> Prioritize prefix package config in PKG_CONFIG_PATH search path.

- generate.xml
- templates/shared/common_install_shell_artifacts.gsl
Update zmq minimum version for non-window systems.
Update clang-3.4 specification to clang-3.6.
> Update libbitcoin version to current.

- generate.xml
- templates/shared/common_install_shell_artifacts.gsl
Update clang compiler version to 5.0.
> Explicitly quote the ICU_LIB shell expansion (resolves #1130).

- templates/gsl.install.sh
- templates/shared/common_install_shell_artifacts.gsl
Thanks to @ldz1 for pointing out the tool - this reproduces changes present in #204 related only to shellcheck warnings.
> Reduce shellcheck warnings.

- templates/gsl.install.sh
- templates/shared/common_install_shell_artifacts.gsl
PR related to https://github.com/libbitcoin/libbitcoin-build/issues/209
New utility functions were created.
> Error activation / deactivation in functions

- templates/gsl.install.sh
- templates/shared/common_install_shell_artifacts.gsl
Further work on https://github.com/libbitcoin/libbitcoin-build/issues/209
- Parameter parsing is in a separate function.
> Function instead of plain code (environment init)

- templates/gsl.install.sh
- templates/shared/common_install_shell_artifacts.gsl
Related to https://github.com/libbitcoin/libbitcoin-build/issues/209
> Environment preparation is in small functions

- gsl.copy_properties.sh
- Remove unused function inside copy_properties.
- Remove unneeded nests in the output file.
> Refactoring of gsl.copy_properties.sh

- gsl.copy_modules.sh
- Macros end with comment for consistency with another gsl scripts.
- Colorized output similar to .cmd.
- No indent similiar to .cmd.
> Rationalization of Windows and Linux scripts.

- generate.cmd
Comments look like copy&paste from linux script.
> Remove unnecessary comments.

- gsl.copy_properties.cmd
- templates/gsl.install.sh
- templates/shared/common_install_shell_artifacts.gsl
Additionally restores hook used in private build script.
> Fixes error in gsl.copy_properties.cmd

- templates/gsl.install-cmake.sh
- templates/gsl.install.sh
- templates/shared/common_install_shell_artifacts.gsl
Reduces output by default.  Enable expanded output for debug with --verbose.
> Install verbosity

- generate4.xml
> Remove pedantic warnings from all projects due to Boost.

- templates/gsl.install.sh
Address libbitcoin/libbitcoin-server/issues/562
> Correct erroneous exclusion of main project on non-CI builds.

- .github/workflows/ci.yml
- generate3.xml
- generate4.xml
- templates/gsl.CMakeLists.txt
- templates/gsl.ci.yml
Specifically libbitcoin/libbitcoin-system#1382 and libbitcoin/libbitcoin-system#1389
> Addresses libbitcoin-system issues

- gsl.copy_properties.cmd
> Fix build_base.bat copy on windows systems.

- generate3.xml
- generate4.xml
- templates/gsl.CMakeLists.txt
- templates/gsl.developer_setup.sh
- templates/gsl.install-cmake.sh
- templates/gsl.install-cmakepresets.sh
- templates/gsl.install.sh
- templates/shared/common_install_shell_artifacts.gsl
Addresses libbitcoin/libbitcoin-system#1381 and libbitcoin/libbitcoin-system#1383
> Add flags to build instructions

- props/version3/project/libbitcoin-blockchain/libbitcoin-blockchain-test/libbitcoin-blockchain-test.props
- props/version3/project/libbitcoin-client/libbitcoin-client-test/libbitcoin-client-test.props
- props/version3/project/libbitcoin-consensus/libbitcoin-consensus-test/libbitcoin-consensus-test.props
- props/version3/project/libbitcoin-database/libbitcoin-database-test/libbitcoin-database-test.props
- props/version3/project/libbitcoin-explorer/libbitcoin-explorer-test/libbitcoin-explorer-test.props
- props/version3/project/libbitcoin-network/libbitcoin-network-test/libbitcoin-network-test.props
- props/version3/project/libbitcoin-node/libbitcoin-node-test/libbitcoin-node-test.props
- props/version3/project/libbitcoin-protocol/libbitcoin-protocol-test/libbitcoin-protocol-test.props
- props/version3/project/libbitcoin-server/libbitcoin-server-test/libbitcoin-server-test.props
- props/version3/project/libbitcoin-system/libbitcoin-system-test/libbitcoin-system-test.props
- props/version4/project/libbitcoin-blockchain/libbitcoin-blockchain-test/libbitcoin-blockchain-test.props
- props/version4/project/libbitcoin-client/libbitcoin-client-test/libbitcoin-client-test.props
- props/version4/project/libbitcoin-consensus/libbitcoin-consensus-test/libbitcoin-consensus-test.props
- props/version4/project/libbitcoin-database/libbitcoin-database-test/libbitcoin-database-test.props
- props/version4/project/libbitcoin-explorer/libbitcoin-explorer-test/libbitcoin-explorer-test.props
- props/version4/project/libbitcoin-network/libbitcoin-network-test/libbitcoin-network-test.props
- props/version4/project/libbitcoin-node/libbitcoin-node-test/libbitcoin-node-test.props
- props/version4/project/libbitcoin-protocol/libbitcoin-protocol-test/libbitcoin-protocol-test.props
- props/version4/project/libbitcoin-server/libbitcoin-server-test/libbitcoin-server-test.props
- props/version4/project/libbitcoin-system/libbitcoin-system-test/libbitcoin-system-test.props
- templates/gsl.CMakeLists.txt
- templates/gsl.ci.yml
- templates/gsl.runner.sh
Addresses libbitcoin/libbitcoin-system#1280
> Set log_level=warning, enabling BOOST_WARN output.

- generate3.xml
- generate4.xml
- templates/gsl.CMakeLists.txt
- templates/gsl.configure.ac
- templates/gsl.install-cmakepresets.sh
- templates/shared/common_install_shell_artifacts.gsl
Fixes #312 directly, libbitcoin/libbitcoin-node#654 by altering `pkg-config` information from `libbitcoin-system`
> Address #312, libbitcoin/libbitcoin-node#654
